### ISSUE TITLE
Ignore certain errors

### ISSUE THREAD

**Issue by Tigger2014** [mtik00/storcli-check#11]
Is it possible to add a way to ignore certain errors, for example im using non certified drives and ideally still want to report on any other errors but this forces me to always error.
Here is an example of the event
```
seqNum: 0x0000031c
Seconds since last reboot: 16
Code: 0x000000ec
Class: 1
Locale: 0x02
Event Description: PD 07(e0xff/s7) is not a certified drive
Event Data:
===========
Device ID: 7
Enclosure Index: 255
Slot Number: 7
```

**Comment by mtik00** [comment]
It's possible, sure.  Not that I can do it, however, here's what I would suggest:

1. Create a new variable to hold some kind of *ignore event* regex
2. Modify `Controller._parse_events()` to determine whether or not the event should be ignored.

Maybe check one of the forks to see if anyone else is actively maintaining this script?

**Comment by mtik00** [comment]
If you have any other issues, please try one of the forks.

NOTE: As of 13-JUL-2018, I no longer have access to MR controllers; This repo should be considered deprecated
