### ISSUE TITLE
Error/warning after zipping

### ISSUE THREAD

**Issue by GunterO** [mtik00/storcli-check#12]
Thanks for your script. 
However, I receive some kind of error/warning:
```
Traceback (most recent call last):
  File "storcli_check.py3", line 741, in <module>
    list(zip([working_directory, LOGFILE], zipped_log_path))
TypeError: 'NoneType' object is not iterable
```

This when I use: 
python storcli_check.py3 --force

No error (obviously) when:
python storcli_check.py3 --force --no-attachments

Any idea's? Thanks!

**Comment by GunterO** [comment]
BTW, your "usage" section is not mentioning the "--no-attachments" option :-)

**Comment by mtik00** [comment]
I suggest trying one of the forks.

For example, @tpdownes implemented the PY3 port.

**NOTE: As of 13-JUL-2018, I no longer have access to MR controllers; This repo should be considered deprecated**
