### ISSUE TITLE
In sendmail function, attachments=None will trigger exception

### ISSUE THREAD

**Issue by orodbhen** [mtik00/storcli-check#4]
First off, thanks for the great utility. You saved me a ton of time. 

Line 245 of `storcli_check.py` should be:

    attachments = attachments or []

Other wise, if `attachments` is `None`, it will be set to `None` again, instead of `[]`.

I disabled the attachments for my environment, but perhaps a command line argument to do this would be better. I just prefer to store it all in a log file locally.

**Comment by mtik00** [comment]
Sorry it took so long... ya, thanks!
