### ISSUE TITLE
How to exclude certain controllers that give errors.

### ISSUE THREAD

**Issue by wrighrc** [mtik00/storcli-check#8]
Hello Timothy,
I upgraded storcli and now storcli-check reports errors on controllers that I do not want to check. 
 
Can you please advise on how to best get around the errors I'm getting?

From the  show all below I do not want to check any N2226 HBAs, which storcli-check now reports
errors on like this:

Controller( 500605b00b1ade90) status: 'ok' not in ['optimal']
ERROR: No VD info!
ERROR: No PD info!

show all output:
System Overview :
===============

--------------------------------------------------------------------------
Ctl Model          Ports PDs DGs DNOpt VDs VNOpt BBU sPR DS EHS ASOs Hlth 
--------------------------------------------------------------------------
  0 ServeRAIDM5210     8   2   1     0   7     0 Opt On  -  Y      2 Opt  
--------------------------------------------------------------------------

IT System Overview :
==================

------------------------------------------------------------------------
Ctl Model     AdapterType   VendId DevId SubVendId SubDevId PCI Address 
------------------------------------------------------------------------
  1 N2226 HBA   SAS3008(C0) 0x1000  0x97    0x1014    0x4CD 00:83:00:00 
  2 N2226 HBA   SAS3008(C0) 0x1000  0x97    0x1014    0x4CD 00:85:00:00 
  3 N2226 HBA   SAS3008(C0) 0x1000  0x97    0x1014    0x4CD 00:88:00:00 
  4 N2226 HBA   SAS3008(C0) 0x1000  0x97    0x1014    0x4CD 00:8a:00:00 
  5 N2226 HBA   SAS3008(C0) 0x1000  0x97    0x1014    0x4CD 00:8d:00:00 
  6 N2226 HBA   SAS3008(C0) 0x1000  0x97    0x1014    0x4CD 00:8f:00:00 
------------------------------------------------------------------------

Thanks.
Charles.

**Comment by mtik00** [comment]
Ya, `storcli` now shows HBAs as well as RAID controllers.  I never planned for that :(

I could probably add a setting for that pretty easily.

If you're comfortable with it, would you attach the output (as a file) from `storcli64 /c1 show all`?  That would help me parse the text to determine if the controller is MR or IT.  I can probably just scrape the name for `HBA`.

**Comment by wrighrc** [comment]
Here's the show all.    Thanks.

[c1showall.txt](https://github.com/mtik00/storcli-check/files/1992181/c1showall.txt)

**Comment by mtik00** [comment]
Ah, IBM, dang... ok (can't use the model name).

I'll whip up a solution that checks the driver.  Have to run to a meeting, but I should have something working in a bit.  No workaround I can think of for time being, sorry.

**Comment by mtik00** [comment]
OK.  The new script should just work.  I'm keying off of the driver name.

If that doesn't work, you have a new CLI option `--ignore`.  In your case, this would probably work:
`python storcli_check.py --ignore 1,2,3,4,5,6`

**Comment by wrighrc** [comment]
Very nice.   Thanks a lot.   I've pulled the new version and it looks good.
