### ISSUE TITLE
Controller not found results in "MR Check Result: PASS" email

### ISSUE THREAD

**Issue by wrighrc** [mtik00/storcli-check#9]
Hi Timothy,
    I found a couple of our servers that storcli-check reports PASS for but had no controller detected.    Weird thing is that it emailed me the PASS.   (Turns out I have to use sas2ircu to check those and not your script/storcli).    I think your script should consider finding 0 controllers to be a failure and squawk about it as a failure rather than squawking about it as a pass.  (if new --ignore ends up ignores everything that should probable be a failure reported too.)    Presently it is sending an email for a PASS (which I wouldn't expect without the --force option)

Maybe the reporting of no controller as a PASS is new, the old version wasn't sending email and I'm not calling with the --force option.

Here are the logs attached to the email.

[logs.zip](https://github.com/mtik00/storcli-check/files/1996213/logs.zip)

Thanks again for solving #8 for me so quickly.
Have a good weekend.
Charles.

**Comment by mtik00** [comment]
Sorry, been quite busy.  I should be able to fix this in a ~day or so~ bit.

**Comment by mtik00** [comment]
Ok, so, that didn't go well, I apologize.

I've left the company I was with and no longer have access to a machine to test this out on.  I'll gladly accept a PR, but I can no longer test any changes.
